name: Build Kivy APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker
        run: docker --version

      - name: Build APK with Kivy Docker
        run: |
          docker pull kivy/buildozer
          docker run --rm -v ${{ github.workspace }}:/home/user/app \
            kivy/buildozer buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Ralenario1-apk
          path: bin/*.apk
