name: Build Kivy APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install system deps
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          unzip zip git openjdk-11-jdk \
          python3-pip python3-setuptools python3-wheel \
          build-essential libffi-dev

    - name: Install Android SDK Commandline Tools
      run: |
        export ANDROID_SDK_ROOT=$HOME/android-sdk
        mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d $ANDROID_SDK_ROOT/cmdline-tools
        mv $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools/latest
        echo "export ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
        echo "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" >> $GITHUB_PATH

    - name: Accept Android SDK Licenses + Install platforms
      run: |
        yes | sdkmanager --licenses
        yes | sdkmanager "platforms;android-30" "build-tools;30.0.3"

    - name: Install Python deps
      run: |
        pip install --upgrade pip
        pip install buildozer Cython

    - name: Build APK (debug)
      run: |
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Ralenior1-apk
        path: bin/*.apk
