name: Build Kivy APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install system deps
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip zip git openjdk-11-jdk \
          python3-pip python3-setuptools build-essential libffi-dev

    - name: Install Android SDK
      run: |
        # Descargar command line tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-9123335_latest.zip -O cmdline-tools.zip
        mkdir -p $HOME/android-sdk/cmdline-tools
        unzip -q cmdline-tools.zip -d $HOME/android-sdk/cmdline-tools
        mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest

        # Exportar paths
        export ANDROID_SDK_ROOT=$HOME/android-sdk
        export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH

        # Instalar componentes necesarios
        yes | sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses
        yes | sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platforms;android-30" "build-tools;30.0.3" "platform-tools"

        # Crear carpeta donde buildozer espera los build-tools
        mkdir -p /home/runner/.buildozer/android/platform/android-sdk/build-tools/30.0.3
        cp -r $ANDROID_SDK_ROOT/build-tools/30.0.3/* /home/runner/.buildozer/android/platform/android-sdk/build-tools/30.0.3/

    - name: Install Python deps
      run: |
        pip install --upgrade pip
        pip install buildozer Cython

    - name: Build APK (debug)
      run: |
        export ANDROID_SDK_ROOT=$HOME/android-sdk
        export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Ralenior1-APK
        path: bin/*.apk
