name: Build Kivy APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build APK in Docker (kivy/buildozer)
        run: |
          docker pull kivy/buildozer:latest
          docker run --rm \
            -v "${{ github.workspace }}:/home/user/app" \
            kivy/buildozer:latest \
            bash -lc "pip install --upgrade pip && buildozer -v android debug"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: bin/*.apk
