name: Build Kivy APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Java 17 para Gradle/Android
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # Python 3.10 (compatible con buildozer/p4a)
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Dependencias del sistema que suelen faltar
      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git build-essential zip unzip ccache \
            libssl-dev libffi-dev libbz2-dev libreadline-dev \
            zlib1g-dev liblzma-dev libsqlite3-dev

      # Acelera builds posteriores (SDK/NDK/gradle dentro de .buildozer)
      - name: Cache .buildozer
        uses: actions/cache@v4
        with:
          path: .buildozer
          key: buildozer-${{ runner.os }}-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            buildozer-${{ runner.os }}-

      # Cache de Gradle (para que no descargue todo cada vez)
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      # Buildozer + Cython y ruedas básicas
      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install --upgrade cython buildozer

      # Compilar APK en modo debug con log verboso
      - name: Build APK (debug)
        env:
          # Evita prompts interactivos de Gradle/SDK
          GRADLE_OPTS: "-Dorg.gradle.jvmargs='-Xmx3g -XX:+UseParallelGC'"
        run: |
          buildozer -v android debug

      # Subir el APK generado
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Ralenior1-apk
          path: bin/*.apk
